# Which tracks to generate
TRACKS := e22j25 e22j26 e22g18 e22b19 e22c20 e22e22 e22d23 e22a26 e22f27

# Revision of correlation run, e.g., v1a, gold253, gold261, gold262
# REV  := v1
REV := FRINGE

# Release version, e.g., 1
REL  := 0

# Name of site; used for ./filelists_<SITE>/
SITE := mpifr

# Top-level directory for Correlator output, any experiment
EXPROOT := /Exps/

